---
title: "Figure 1- Environmental factors- Temp (2-m depth) and DHWs"
author: "Coral NRG NRK"
date: "2024-12-11"
output: html_document
---

```{r, echo=FALSE}
library(utils)
library(pacman)
library(ggplot2)
library(lme4)
library(lmerTest)
library(MuMIn)
library(dplyr)
library(tidyverse)
library(stats)
library(mvabund)
library(lmerTest)
library(mvabund)
library (dplyr)
library(car)
library(rstatix)
library(ggplot2)
library(tidyr)
library(visreg)
library(rstatix)
library(PMCMRplus)
library(PMCMR)
library(viridis)
library(RColorBrewer)
library(Rmisc)
library(cowplot)
library(utils)
library(vegan)
library(readr)
library(predictmeans)
library(emmeans)
library(scales)
library(lubridate)
library(openxlsx)

```


```{r}
Temp <- read.csv("Env_factors_Temp_DHWs_Chl_NMP_NOAA_untilSep2024.csv")

head(Temp)


class(Temp$Date)



Temp$Date = as.Date(Temp$Date, format=  "%d/%m/%Y")



Temp$Water_Temp_Max <- as.numeric(as.character(Temp$Water_Temp_Max))
Temp$Water_Temp_Min <- as.numeric(as.character(Temp$Water_Temp_Min))
Temp$DHW <- as.numeric(as.character(Temp$DHW))


colnames(Temp)
head(Temp)

Sys.setlocale("LC_TIME", "English")

```

```{r}

vertical_line_dates <- as.Date(c("2021/02/04" ,"2021/07/01", "2021/08/03", "2022/01/09",
                                 "2022/07/14", "2022/07/28", "2022/08/10", "2022/08/24", 
                                 "2023/07/09", "2023/07/25", "2023/08/10", "2023/08/22", "2024/01/09",  format= "%Y/%m/%d")) 

```


```{r}

Temp__plot=
  ggplot()+
  geom_line(data= Temp, aes(x=Date, y=Water_Temp_Max))+
   theme(axis.title.x = element_blank())+
    labs(y="Temperature (°C)")+
    scale_x_date( date_breaks = "2 month", date_labels = "%b %y", limits = NULL)+
      theme_classic(base_size = 16)+
  theme(axis.title.x = element_blank())+
  theme(legend.position = "none")+
   theme(axis.text.x=element_text(angle=60, hjust=1))+
    geom_hline(yintercept = c(27.55), size=0.5)+
  scale_y_continuous(limits=c(21, 31),
                     breaks = c(21, 22, 23, 24, 25, 26, 27,28,29,30,31))+
   geom_vline(xintercept = vertical_line_dates, linetype="dashed")

Temp__plot

ggsave("Temp__plot.jpeg", width=20, height= 10, units= "cm", dpi=600)
```


```{r}
DHW_plot=
  ggplot()+
  geom_line(data= Temp, aes(x=Date, y=DHW))+
   theme(axis.title.x = element_blank())+
    labs(y="DHW")+
    scale_x_date( date_breaks = "2 month", date_labels = "%b %y")+
      theme_classic(base_size = 16)+
  theme(axis.title.x = element_blank())+
  theme(legend.position = "none")+
   theme(axis.text.x=element_text(angle=60, hjust=1))+
    geom_hline(yintercept = 4, linetype="dashed", size=0.5)+
  geom_hline(yintercept = 8,  size=0.5)+
  scale_y_continuous(breaks = c(0,4,8,12,16, 20, 25, 30, 35))+
  geom_vline(xintercept = vertical_line_dates, linetype="dashed")
DHW_plot

ggsave("DHW_plot.jpeg", width=20, height= 10, units= "cm", dpi=600)
```





